name: Deploy to Production

# Update every time we push to the main branch
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:

    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@v2
      id: deployment
      with:
        token: ${{ github.token }}
        environment: production

    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Pull latest changes to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} /bin/bash << 'EOF'
          # Causes this script to exit early and report a failure if any command errors
          set -e

          # Checkout latest changes from our repo, overwriting any local changes
          cd "$HOME/src/github.com/eritbh/twitter-rss"
          git fetch --all
          git reset --hard origin/main

          # Trigger the rebuild with the new contents
          sudo systemctl restart twitter-rss.service
        EOF

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ github.token }}
        state: success
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ github.token }}
        state: failure
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
